#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Checker for the two negative-knowledge concept types, dead-end and
field-state: the attribution-shaped record of what did not work and of
what the field has not settled.

A dead-end says: this goal was attempted by this method, it failed with
this symptom for this cause (or an unknown one), it was observed on
these dates by these actors in these threads, and here is what would
reopen it. A field-state says: as of this date the field holds these
positions on this question, held by these sources, and here is what
would move the state. Neither type adjudicates. The truth condition of
both is attribution: the record is true when the cited attempts and
positions exist and say what the concept says they say, whether or not
the underlying approach turns out viable or the question gets settled.
That is why a stable dead-end is deprecated by a `reopened` block, never
deleted, and why a field-state that carries a verdict fails outright.

Both carry `load_bearing` (high, medium, low), the count of how much in
the bundle depends on the entry, on the same footing as a gotcha's
severity: high requires a matching eval case id, so an agent that
retries a high dead-end or picks a side in a high field-state is
measured, not just told.

Usage:
  check_negative.py ROOT [--bundle BUNDLE] [--explain]
  check_negative.py --candidates PATH... [--out DIR]
  check_negative.py --selftest

ROOT is scanned for concepts whose `type` is dead-end or field-state;
other concepts are left alone. Paths in `subject`, `bears_on`,
`superseded_by` and `sources` resolve relative to the concept file, or,
with a leading slash, relative to BUNDLE (default ROOT), so drafts kept
outside a bundle can point into one. Exit 0 when no N code fires.

Codes beginning N are errors, NW are warnings:

  N1  required field missing or malformed (both: title, description,
      status, load_bearing, sources; dead-end: subject, attempt with
      goal and method, failure with symptom and cause, observations,
      reopens_if; field-state: question, as_of, state, positions,
      stale_after)
  N2  attribution incomplete: an observation without a date (at), an actor
      (`human:`, `process:` or tool/version form) and a source id; a
      question that is not one sentence ending in a question mark; a
      position without a statement, holders and sources; as_of not a
      date
  N3  citation broken: an observation or position cites a source id
      that is not in sources; a source is never cited from the body
      (footnote form); a footnote in the body names no source
  N4  load_bearing not high, medium or low; high without eval_case
  N5  a field-state adjudicates: a claim, verdict, answer, resolution,
      adjudication, winner or consensus key, or a body section headed
      that way; state disputed with fewer than two positions
  N6  a stable concept has no `human:` verified event, or verified is
      malformed
  N7  ladder inconsistent: deprecated without superseded_by (or, on a
      dead-end, a reopened block with at, human by and evidence);
      superseded_by or reopened on a concept that is not deprecated;
      a deprecated dead-end with a reopened block but no Reopened
      section
  N8  body sections missing or out of order (dead-end: Attempted,
      Observed, Why it fails, Reopens if, with Do instead optional
      before Reopens if; field-state: Question, Positions, Bearing,
      What would move this)
  N9  a subject, bears_on or superseded_by path resolves to no concept
  NW1 a dead-end without stale_after (tools get fixed; date the sweep)
  NW2 title or description phrased as a universal (impossible, never
      works, cannot be done) rather than an attribution
  NW3 a high load-bearing dead-end with no Do instead section
  NW4 every position of a field-state rests on the same single source

--candidates scans text for dead-end phrasings (retracted, does not
work, gave up, proves nothing, workaround and the like) and lists the
matched lines; with --out it drafts one candidate stub per file in the
same shape the community miner uses, status draft, generated by a
process actor, for a steward to keep or discard. It never writes into
a bundle.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

TYPES = ("dead-end", "field-state")
LOAD = ("high", "medium", "low")
STATES = ("disputed", "open", "converging")
ADJUDICATION_KEYS = ("claim", "verdict", "answer", "resolution",
                     "adjudication", "winner", "consensus")
ADJUDICATION_HEADS = ("verdict", "conclusion", "answer", "resolution",
                      "adjudication", "our position", "the answer")
UNIVERSAL = ("impossible", "never works", "cannot be done", "can't be done",
             "no way to", "will never")
DEAD_END_SECTIONS = ["Attempted", "Observed", "Why it fails", "Reopens if"]
FIELD_STATE_SECTIONS = ["Question", "Positions", "Bearing", "What would move this"]
LEXICON = ("retract", "dead end", "dead-end", "does not work", "did not work",
           "doesn't work", "didn't work", "gave up", "abandon", "fails because",
           "failed because", "not viable", "unworkable", "proves nothing",
           "workaround", "no longer works")
FOOTNOTE_REF = re.compile(r"\[\^([A-Za-z0-9][A-Za-z0-9_.-]*)\](?!:)")
FOOTNOTE_DEF = re.compile(r"^\[\^([A-Za-z0-9][A-Za-z0-9_.-]*)\]:", re.M)
HEADING = re.compile(r"^#\s+(.+?)\s*$", re.M)
ACTOR = re.compile(r"^[A-Za-z][A-Za-z0-9_.-]*[:/][^\s]+$")
FENCE = re.compile(r"```.*?```", re.S)


def frontmatter(path: Path):
    """Return (frontmatter dict, body) or (None, reason)."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None, "no frontmatter"
    end = text.find("\n---\n", 4)
    if end < 0:
        return None, "unterminated frontmatter"
    try:
        fm = yaml.safe_load(text[4:end])
    except yaml.YAMLError as e:
        return None, f"frontmatter is not YAML: {e}"
    if not isinstance(fm, dict):
        return None, "frontmatter is not a mapping"
    return fm, text[end + 5:]


def is_date(v) -> bool:
    if isinstance(v, (dt.date, dt.datetime)):
        return True
    return isinstance(v, str) and re.fullmatch(r"\d{4}-\d{2}-\d{2}(T[0-9:.]+Z?)?", v) is not None


def is_actor(v) -> bool:
    return isinstance(v, str) and ACTOR.match(v) is not None


def resolve(ref: str, here: Path, bundle: Path) -> Path | None:
    """A concept path: bundle-relative with a leading slash, else relative
    to the citing file. Fragments and URLs are not concept paths."""
    if not isinstance(ref, str) or "://" in ref or not ref:
        return None
    ref = ref.split("#", 1)[0]
    target = (bundle / ref.lstrip("/")) if ref.startswith("/") else (here.parent / ref)
    return target if target.is_file() else None


def sections(body: str) -> list[str]:
    return [m.group(1) for m in HEADING.finditer(FENCE.sub("", body))]


def in_order(found: list[str], required: list[str]) -> bool:
    pos = -1
    for name in required:
        try:
            pos = found.index(name, pos + 1)
        except ValueError:
            return False
    return True


class Report:
    def __init__(self):
        self.errors: list[tuple[str, str, str]] = []
        self.warns: list[tuple[str, str, str]] = []
        self.notes: list[str] = []

    def err(self, code, path, msg):
        self.errors.append((code, str(path), msg))

    def warn(self, code, path, msg):
        self.warns.append((code, str(path), msg))


def check_common(fm: dict, body: str, path: Path, rep: Report) -> dict:
    """The checks both types share. Returns the citation summary."""
    for key in ("title", "description"):
        if not isinstance(fm.get(key), str) or not fm[key].strip():
            rep.err("N1", path, f"{key} missing or empty")
    status = fm.get("status")
    if status not in ("draft", "stable", "deprecated"):
        rep.err("N1", path, f"status must be draft, stable or deprecated (got {status!r})")
    load = fm.get("load_bearing")
    if load not in LOAD:
        rep.err("N4", path, f"load_bearing must be one of {', '.join(LOAD)} (got {load!r})")
    elif load == "high" and not (isinstance(fm.get("eval_case"), str) and fm["eval_case"].strip()):
        rep.err("N4", path, "load_bearing high requires eval_case naming the case that "
                            "measures the behavior this entry is meant to change")

    ids: list[str] = []
    sources = fm.get("sources")
    if not isinstance(sources, list) or not sources:
        rep.err("N1", path, "sources must be a non-empty list")
        sources = []
    for i, s in enumerate(sources):
        if not isinstance(s, dict) or not s.get("id") or not s.get("resource") or not s.get("title"):
            rep.err("N1", path, f"sources[{i}] needs id, resource and title")
            continue
        if s["id"] in ids:
            rep.err("N3", path, f"duplicate source id {s['id']}")
        ids.append(s["id"])
    cited = set(FOOTNOTE_REF.findall(FENCE.sub("", body)))
    defined = set(FOOTNOTE_DEF.findall(body))
    for sid in ids:
        if sid not in cited:
            rep.err("N3", path, f"source {sid} is never cited from the body (write [^{sid}] "
                                "where the record relies on it)")
    for ref in sorted(cited - set(ids)):
        rep.err("N3", path, f"footnote [^{ref}] names no source")
    for ref in sorted(cited - defined):
        rep.err("N3", path, f"footnote [^{ref}] has no definition line")

    verified = fm.get("verified")
    events = verified if isinstance(verified, list) else ([verified] if verified is not None else [])
    human = False
    for ev in events:
        if not isinstance(ev, dict) or not is_actor(ev.get("by")) or not is_date(ev.get("at")):
            rep.err("N6", path, "verified event needs an actor `by` and a date `at`")
            continue
        human = human or ev["by"].startswith("human:")
    if status == "stable" and not human:
        rep.err("N6", path, "a stable negative-knowledge concept carries a human: verified "
                            "event; nobody but the steward signs")

    if status == "deprecated":
        if not fm.get("superseded_by") and not fm.get("reopened"):
            rep.err("N7", path, "deprecated without superseded_by" +
                    (" or a reopened block" if fm.get("type") == "dead-end" else ""))
    else:
        for key in ("superseded_by", "reopened"):
            if fm.get(key):
                rep.err("N7", path, f"{key} on a concept that is not deprecated")
    if fm.get("reopened") and fm.get("type") != "dead-end":
        rep.err("N7", path, "reopened belongs to dead-ends; a field-state is superseded")

    for key in ("title", "description"):
        low = str(fm.get(key) or "").lower()
        hit = next((u for u in UNIVERSAL if u in low), None)
        if hit:
            rep.warn("NW2", path, f"{key} reads as a universal ({hit!r}); the attribution "
                                  "shape says who tried what and when")
    return {"ids": ids, "cited": sorted(cited), "status": status, "load": load}


def check_dead_end(fm: dict, body: str, path: Path, bundle: Path, rep: Report, summary: dict):
    subject = fm.get("subject")
    if not isinstance(subject, list) or not subject:
        rep.err("N1", path, "subject must be a non-empty list of concept paths")
        subject = []
    resolved = []
    for ref in subject:
        target = resolve(ref, path, bundle)
        if target is None:
            rep.err("N9", path, f"subject {ref} resolves to no concept")
        else:
            resolved.append(str(target))
    summary["subject"] = resolved

    attempt = fm.get("attempt")
    if not isinstance(attempt, dict) or not all(
            isinstance(attempt.get(k), str) and attempt[k].strip() for k in ("goal", "method")):
        rep.err("N1", path, "attempt needs goal and method")
    failure = fm.get("failure")
    if not isinstance(failure, dict) or not all(
            isinstance(failure.get(k), str) and failure[k].strip() for k in ("symptom", "cause")):
        rep.err("N1", path, "failure needs symptom and cause (cause may be the word unknown)")
    if not (isinstance(fm.get("reopens_if"), str) and fm["reopens_if"].strip()):
        rep.err("N1", path, "reopens_if names the change that would make this worth retrying")

    obs = fm.get("observations")
    if not isinstance(obs, list) or not obs:
        rep.err("N1", path, "observations must be a non-empty list of {at, by, source}")
        obs = []
    for i, o in enumerate(obs):
        if not isinstance(o, dict):
            rep.err("N2", path, f"observations[{i}] is not a mapping")
            continue
        if not is_date(o.get("at")):
            rep.err("N2", path, f"observations[{i}].at is not a date")
        if not is_actor(o.get("by")):
            rep.err("N2", path, f"observations[{i}].by is not an actor (human:, process: or tool/version)")
        if not o.get("source"):
            rep.err("N2", path, f"observations[{i}] cites no source id")
        elif o["source"] not in summary["ids"]:
            rep.err("N3", path, f"observations[{i}] cites source {o['source']}, not in sources")

    found = sections(body)
    required = list(DEAD_END_SECTIONS)
    if "Do instead" in found:
        required.insert(3, "Do instead")
    if fm.get("reopened"):
        required.append("Reopened")
    if not in_order(found, required):
        rep.err("N8", path, f"body sections must run {', '.join(required)} in that order "
                            f"(found {', '.join(found[1:]) or 'none'})")
    summary["sections"] = found[1:]

    reopened = fm.get("reopened")
    if reopened is not None:
        if (not isinstance(reopened, dict) or not is_date(reopened.get("at"))
                or not (is_actor(reopened.get("by")) and reopened["by"].startswith("human:"))
                or not reopened.get("evidence")):
            rep.err("N7", path, "reopened needs at, a human: by, and evidence")
        if "Reopened" not in found:
            rep.err("N7", path, "a reopened dead-end carries a Reopened section saying what changed")
    if fm.get("superseded_by") and resolve(fm["superseded_by"], path, bundle) is None:
        rep.err("N9", path, f"superseded_by {fm['superseded_by']} resolves to no concept")

    if not fm.get("stale_after"):
        rep.warn("NW1", path, "no stale_after: a dead-end is dated by the tool and product "
                              "versions it was observed on")
    elif not is_date(fm["stale_after"]):
        rep.err("N1", path, "stale_after is not a date")
    if summary.get("load") == "high" and "Do instead" not in found:
        rep.warn("NW3", path, "a high load-bearing dead-end with no Do instead section leaves "
                              "the reader at the wall")


def check_field_state(fm: dict, body: str, path: Path, bundle: Path, rep: Report, summary: dict):
    q = fm.get("question")
    if not isinstance(q, str) or not q.strip():
        rep.err("N1", path, "question missing")
    elif not q.strip().endswith("?") or q.strip().count("?") != 1 or re.search(r"[.!]\s+\S", q.strip()):
        rep.err("N2", path, "question is one sentence ending in a question mark")
    if not is_date(fm.get("as_of")):
        rep.err("N2", path, "as_of must be the date the state of discourse was read")
    if fm.get("state") not in STATES:
        rep.err("N1", path, f"state must be one of {', '.join(STATES)} (got {fm.get('state')!r})")
    if not fm.get("stale_after"):
        rep.err("N1", path, "a field-state carries stale_after: a statement about current "
                            "discourse is dated by nature")
    elif not is_date(fm["stale_after"]):
        rep.err("N1", path, "stale_after is not a date")

    for key in ADJUDICATION_KEYS:
        if key in fm:
            rep.err("N5", path, f"a field-state does not adjudicate: drop the {key} key; the "
                                "signature attests the state of discourse, not a side")
    found = sections(body)
    for head in found:
        if head.strip().lower() in ADJUDICATION_HEADS:
            rep.err("N5", path, f"a field-state does not adjudicate: section {head!r}")

    positions = fm.get("positions")
    if not isinstance(positions, list) or not positions:
        rep.err("N1", path, "positions must be a non-empty list")
        positions = []
    if fm.get("state") == "disputed" and len(positions) < 2:
        rep.err("N5", path, "state disputed with fewer than two positions is a claim wearing "
                            "a field-state's clothes")
    pids: list[str] = []
    source_sets: list[tuple] = []
    for i, p in enumerate(positions):
        if not isinstance(p, dict):
            rep.err("N2", path, f"positions[{i}] is not a mapping")
            continue
        if not p.get("id") or p["id"] in pids:
            rep.err("N2", path, f"positions[{i}] needs a unique id")
        else:
            pids.append(p["id"])
        if not (isinstance(p.get("statement"), str) and p["statement"].strip()):
            rep.err("N2", path, f"positions[{i}] needs a statement")
        if not (isinstance(p.get("held_by"), list) and p["held_by"]):
            rep.err("N2", path, f"positions[{i}] needs held_by, who holds it")
        srcs = p.get("sources")
        if not (isinstance(srcs, list) and srcs):
            rep.err("N2", path, f"positions[{i}] needs sources")
            srcs = []
        for sid in srcs:
            if sid not in summary["ids"]:
                rep.err("N3", path, f"positions[{i}] cites source {sid}, not in sources")
        source_sets.append(tuple(sorted(srcs)))
    if len(positions) >= 2 and len(set(source_sets)) == 1 and len(source_sets[0]) == 1:
        rep.warn("NW4", path, "every position rests on the same single source; a dispute "
                              "read from one document is that document's dispute")
    summary["positions"] = pids

    bears = fm.get("bears_on") or []
    if not isinstance(bears, list):
        rep.err("N1", path, "bears_on must be a list of concept paths")
        bears = []
    resolved = []
    for ref in bears:
        target = resolve(ref, path, bundle)
        if target is None:
            rep.err("N9", path, f"bears_on {ref} resolves to no concept")
        else:
            resolved.append(str(target))
    summary["bears_on"] = resolved
    if fm.get("superseded_by") and resolve(fm["superseded_by"], path, bundle) is None:
        rep.err("N9", path, f"superseded_by {fm['superseded_by']} resolves to no concept")

    if not in_order(found, FIELD_STATE_SECTIONS):
        rep.err("N8", path, f"body sections must run {', '.join(FIELD_STATE_SECTIONS)} in that "
                            f"order (found {', '.join(found[1:]) or 'none'})")
    summary["sections"] = found[1:]


def check_root(root: Path, bundle: Path, explain: bool) -> tuple[Report, dict]:
    rep = Report()
    counts = {t: 0 for t in TYPES}
    for path in sorted(root.rglob("*.md")):
        if any(part in (".git", "node_modules", "__pycache__") for part in path.parts):
            continue
        fm, body = frontmatter(path)
        if fm is None or fm.get("type") not in TYPES:
            continue
        counts[fm["type"]] += 1
        summary = check_common(fm, body, path, rep)
        if fm["type"] == "dead-end":
            check_dead_end(fm, body, path, bundle, rep, summary)
        else:
            check_field_state(fm, body, path, bundle, rep, summary)
        if explain:
            print(f"{fm['type']} {path}")
            print(f"    status {summary['status']}, load_bearing {summary['load']}")
            for key in ("subject", "bears_on", "positions"):
                if summary.get(key) is not None:
                    print(f"    {key}: {', '.join(summary[key]) or 'none'}")
            print(f"    sources cited: {', '.join(summary['cited']) or 'none'}")
            print(f"    sections: {', '.join(summary.get('sections') or []) or 'none'}")
    return rep, counts


def candidates(paths: list[Path], out: Path | None) -> int:
    """Lines that read like a dead end, file by file. Returns the count."""
    total = 0
    for p in paths:
        files = [p] if p.is_file() else sorted(q for q in p.rglob("*") if q.suffix in (".md", ".txt"))
        for f in files:
            hits = []
            for n, line in enumerate(f.read_text(encoding="utf-8", errors="replace").splitlines(), 1):
                low = line.lower()
                phrase = next((w for w in LEXICON if w in low), None)
                if phrase:
                    hits.append((n, phrase, line.strip()))
            for n, phrase, line in hits:
                print(f"{f}:{n}  [{phrase}]  {line[:120]}")
            total += len(hits)
            if out and hits:
                out.mkdir(parents=True, exist_ok=True)
                today = dt.date.today().isoformat()
                obs = "\n".join(f"  - {{ at: {today}, by: process:negative-miner, source: line-{n} }}"
                                for n, _, _ in hits[:8])
                src = "\n".join(f"  - id: line-{n}\n    resource: {f}#L{n}\n    title: \"{line[:70]}\""
                                for n, _, line in hits[:8])
                refs = " ".join(f"[^line-{n}]" for n, _, _ in hits[:8])
                defs = "\n".join(f"[^line-{n}]: {f} line {n}" for n, _, _ in hits[:8])
                stub = f"""---
type: dead-end
title: "CANDIDATE ({f.stem}): {len(hits)} lines read like a dead end"
description: "Drafted from {len(hits)} matched lines in {f.name}; a steward decides whether this is a dead-end, a gotcha, or noise."
tags: [candidate, dead-end, {f.stem}]
status: draft
load_bearing: low
generated: {{ by: process:negative-miner, at: {today}T00:00:00Z }}
subject: []
attempt: {{ goal: "STUB", method: "STUB" }}
failure: {{ symptom: "STUB", cause: unknown }}
observations:
{obs}
reopens_if: "STUB"
sources:
{src}
---

# Candidate: {f.stem}

# Attempted

STUB: the steward writes what was tried, citing the lines. {refs}

# Observed

STUB

# Why it fails

STUB

# Reopens if

STUB

{defs}
"""
                (out / f"candidate-{f.stem}.md").write_text(stub, encoding="utf-8")
    return total


GOOD_DEAD_END = """---
type: dead-end
title: "Summing a box's convergence and comparing it to the rim flux was tried as a budget oracle; it holds for any array"
description: "The discrete divergence identity was used as evidence that a regional budget validates itself; it is algebra and returned exactly zero on random data."
tags: [budgets, regional, oracle]
status: draft
load_bearing: medium
generated: { by: claude-code/test, at: 2026-09-01T00:00:00Z }
stale_after: 2027-03-01
subject: [/datasets/product.md]
attempt:
  goal: "Validate a regional heat budget without an independent reference"
  method: "Compare summed cell convergence to the flux through the box rim"
failure:
  symptom: "Passes bit for bit on random noise"
  cause: "Each interior face is added once and subtracted once from the same stored number"
observations:
  - { at: 2026-09-01, by: claude-code/test, source: design-note }
reopens_if: "Never as an oracle; the identity stays a permission to compute convergence from rim faces"
sources:
  - id: design-note
    resource: https://example.org/design-note
    title: "The design note recording the retraction"
---

# Title

# Attempted

The identity was proposed as the oracle.[^design-note]

# Observed

Exactly zero on random data.

# Why it fails

Algebra, not physics.

# Do instead

Disjoint data paths, two bars, mutation controls.

# Reopens if

Never as an oracle.

[^design-note]: the design note
"""

GOOD_FIELD_STATE = """---
type: field-state
title: "Whether the overturning has weakened over the observational era is disputed"
description: "Three positions with their holders, read on the stated date; the signature attests the state of discourse."
tags: [amoc, discourse]
status: draft
load_bearing: medium
generated: { by: claude-code/test, at: 2026-09-05T00:00:00Z }
stale_after: 2027-03-05
question: "Has the overturning weakened over the observational era?"
as_of: 2026-09-05
state: disputed
positions:
  - id: weakening
    statement: "A weakening is detectable in a proxy fingerprint"
    held_by: ["paper A"]
    sources: [paper-a]
  - id: no-decline
    statement: "The direct record shows no decline"
    held_by: ["paper B"]
    sources: [paper-b]
bears_on: [/datasets/product.md]
sources:
  - id: paper-a
    resource: https://doi.org/10.0000/a
    title: "Paper A"
  - id: paper-b
    resource: https://doi.org/10.0000/b
    title: "Paper B"
---

# Title

# Question

The question.

# Positions

Weakening.[^paper-a] No decline.[^paper-b]

# Bearing

The transport computation.

# What would move this

A longer record.

[^paper-a]: paper A
[^paper-b]: paper B
"""


def selftest() -> int:
    tmp = Path(tempfile.mkdtemp(prefix="check_negative_"))
    try:
        (tmp / "datasets").mkdir()
        (tmp / "datasets" / "product.md").write_text("---\ntype: dataset\ntitle: p\n---\n# p\n")
        (tmp / "dead-ends").mkdir()
        (tmp / "field-states").mkdir()
        (tmp / "dead-ends" / "good.md").write_text(GOOD_DEAD_END)
        (tmp / "field-states" / "good.md").write_text(GOOD_FIELD_STATE)
        rep, counts = check_root(tmp, tmp, explain=False)
        assert counts == {"dead-end": 1, "field-state": 1}, counts
        assert not rep.errors and not rep.warns, (rep.errors, rep.warns)

        def codes(text: str, kind: str) -> set[str]:
            d = tmp / "case"
            shutil.rmtree(d, ignore_errors=True)
            d.mkdir()
            (d / "x.md").write_text(text)
            r, _ = check_root(d, tmp, explain=False)
            return {c for c, _, _ in r.errors} | {c for c, _, _ in r.warns}

        de, fs = GOOD_DEAD_END, GOOD_FIELD_STATE
        cases = [
            (de.replace("  goal: \"Validate", "  goalx: \"Validate"), "N1"),
            (de.replace("by: claude-code/test, source", "by: somebody, source"), "N2"),
            (de.replace("source: design-note }", "source: nowhere }"), "N3"),
            (de.replace("[^design-note]", ""), "N3"),
            (de.replace("load_bearing: medium", "load_bearing: high"), "N4"),
            (de.replace("status: draft", "status: stable"), "N6"),
            (de.replace("status: draft", "status: stable\nverified: { by: process:bot, at: 2026-09-05 }"), "N6"),
            (de.replace("status: draft", "status: deprecated"), "N7"),
            (de.replace("stale_after: 2027-03-01",
                        "stale_after: 2027-03-01\nreopened: { at: 2026-09-05, by: human:steward, evidence: https://example.org/fix }"), "N7"),
            (de.replace("# Why it fails", "# Why"), "N8"),
            (de.replace("subject: [/datasets/product.md]", "subject: [/datasets/missing.md]"), "N9"),
            (de.replace("stale_after: 2027-03-01\n", ""), "NW1"),
            (de.replace("it holds for any array", "it is impossible"), "NW2"),
            (de.replace("load_bearing: medium", "load_bearing: high\neval_case: oracle-retry")
               .replace("# Do instead\n\nDisjoint data paths, two bars, mutation controls.\n\n", ""), "NW3"),
            (fs.replace("as_of: 2026-09-05", "as_of: yesterday"), "N2"),
            (fs.replace("question: \"Has the overturning weakened over the observational era?\"",
                        "question: \"The overturning has weakened.\""), "N2"),
            (fs.replace("state: disputed", "state: disputed\nverdict: weakening"), "N5"),
            (fs.replace("# Bearing", "# Conclusion\n\nWeakening wins.\n\n# Bearing"), "N5"),
            (fs.replace("  - id: no-decline\n    statement: \"The direct record shows no decline\"\n"
                        "    held_by: [\"paper B\"]\n    sources: [paper-b]\n", ""), "N5"),
            (fs.replace("stale_after: 2027-03-05\n", ""), "N1"),
            (fs.replace("sources: [paper-b]", "sources: [paper-a]"), "NW4"),
            (fs.replace("bears_on: [/datasets/product.md]", "bears_on: [/datasets/missing.md]"), "N9"),
            (fs.replace("# What would move this", "# What moves it"), "N8"),
        ]
        for text, want in cases:
            got = codes(text, want)
            assert want in got, f"expected {want}, got {sorted(got)}"
        # A good field-state marked stable with a human signature passes.
        signed = fs.replace("status: draft", "status: stable\nverified: { by: human:steward, at: 2026-09-05T00:00:00Z }")
        assert not (codes(signed, "") & {"N6"}), "human signature must satisfy N6"
        # A dead-end that a field-state key would not fit: reopened on a field-state.
        assert "N7" in codes(fs.replace("status: draft", "status: deprecated\nreopened: { at: 2026-09-05, by: human:s, evidence: x }"), "N7")
        # The candidate scan finds a planted line and drafts a stub that parses.
        sample = tmp / "notes.md"
        sample.write_text("fine line\nwe tried the rim identity and it proves nothing\n")
        out = tmp / "cands"
        import io, contextlib
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            n = candidates([sample], out)
        assert n == 1 and "proves nothing" in buf.getvalue(), buf.getvalue()
        fm, _ = frontmatter(out / "candidate-notes.md")
        assert fm and fm["type"] == "dead-end" and fm["status"] == "draft", fm
        print(f"selftest PASS: {len(cases)} mutations each fired its code; the two exemplars pass "
              "clean; the candidate scan drafts a parseable stub")
        return 0
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("root", nargs="?", type=Path, help="directory to scan for dead-end and field-state concepts")
    ap.add_argument("--bundle", type=Path, help="root for leading-slash paths (default: ROOT)")
    ap.add_argument("--explain", action="store_true", help="print how each concept resolved")
    ap.add_argument("--candidates", nargs="+", type=Path, help="scan these files or directories for dead-end phrasings")
    ap.add_argument("--out", type=Path, help="with --candidates, draft one stub per matched file here")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()
    if args.selftest:
        return selftest()
    if args.candidates:
        n = candidates(args.candidates, args.out)
        print(f"\ncandidate lines: {n}" + (f", stubs in {args.out}" if args.out and n else ""))
        return 0
    if args.root is None:
        ap.error("ROOT, --candidates or --selftest is required")
    if not args.root.is_dir():
        ap.error(f"{args.root} is not a directory")
    bundle = (args.bundle or args.root).resolve()
    rep, counts = check_root(args.root, bundle, args.explain)
    for code, path, msg in rep.errors + rep.warns:
        print(f"{code}  {path}: {msg}")
    print(f"\ndead-ends: {counts['dead-end']}  field-states: {counts['field-state']}")
    print(f"errors: {len(rep.errors)}  warnings: {len(rep.warns)}")
    if rep.errors:
        print("FAIL: an N code above fires; the record is not yet attribution-shaped")
        return 1
    print("PASS: every dead-end and field-state under the root is attribution-shaped"
          + ("; warnings above are SHOULDs, not failures" if rep.warns else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
