#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""mine_sources: harvest ECCO community issues, cluster recurring
confusions, and draft gotcha candidates for the promotion ladder.

Pulls issues (open and closed) from ECCO-GROUP repos via the GitHub API,
buckets them against a topic lexicon of known-confusable ECCO subjects,
and reports clusters by recurrence. With --draft-dir it writes one
candidate stub per cluster that clears --min-hits, each stub carrying its
evidence links (the issue URLs), generated by the miner's process actor,
status draft, unverified tier. Humans decide what is a real trap; the
miner only counts and cites.

Two buckets route to a register instead of the gotcha ladder, and the
report says so beside the count: can-I-use-X-for-Y questions are
validity-domain candidates, and phrasings of an attempt that failed
(tried, gave up, does not work, proves nothing, workaround, retracted)
are dead-end candidates. A routed bucket's stub carries the register's
concept type and names the register (a tracking issue) where a steward
triages it. The dead-end needles are the same lexicon check_negative.py
runs over local text with --candidates; the selftest keeps the two in
step.

Auth: set GITHUB_TOKEN (unauthenticated API rate limits are low). The
forum (ecco-group.org discussion board) has no API; it is read by hand
against the same lexicon.

Usage:
  mine_sources.py [--repos ECCO-GROUP/ECCOv4-py ECCO-GROUP/ECCO-v4-Python-Tutorial]
      [--min-hits 3] [--draft-dir out/] [--selftest]
"""

import argparse
import datetime
import json
import os
import re
import sys
import urllib.request
from pathlib import Path

LEXICON = {
    "interpolated-budgets": ["interpolat", "0.5 deg", "latlon budget", "regrid"],
    "snapshots-and-bookends": ["snapshot", "tendency", "bookend"],
    "geothermal": ["geothermal"],
    "hfac-partial-cells": ["hfac", "partial cell"],
    "release-mixing": ["v4r4b", "r4b", "release 4b", "mix release"],
    "llc-grid-orientation": ["llc", "tile", "face", "rotate", "orientation", "cs sn"],
    "access-auth": ["earthdata", "netrc", "401", "403", "credential", "authenticat"],
    "ecco-access-quirks": ["ecco_access", "ecco_podaac", "download fail", "filename"],
    "units-signs": ["sign convention", "units", "w/m2", "positive down", "positive up"],
    "bolus-transport": ["bolus", "gm ", "gent"],
    # Recurring can-I-use-X-for-Y questions are validity-domain
    # candidates; clusters here go to the validity-domain register
    # (open-science-pillars/marketplace#27), not the gotcha ladder.
    "validity-domain-candidates": ["can i use", "suitable for", "valid for",
                                   "appropriate for", "good enough for",
                                   "fit for", "reliable for", "trust the trend",
                                   "resolve eddies", "resolution enough"],
    # Phrasings of an attempt that failed are dead-end candidates;
    # clusters here go to the dead-end register, not the gotcha ladder.
    # Same needles as check_negative.py --candidates (the selftest checks).
    "dead-end-candidates": ["retract", "dead end", "dead-end", "does not work",
                            "did not work", "doesn't work", "didn't work",
                            "gave up", "abandon", "fails because",
                            "failed because", "not viable", "unworkable",
                            "proves nothing", "workaround", "no longer works"],
}

# Buckets that route to a register rather than the gotcha ladder. The
# register is the tracking issue where a steward triages the cluster;
# a stub drafted for a routed bucket carries the register's concept type
# and names the register. Every other bucket is a gotcha candidate.
REGISTERS = {
    "validity-domain-candidates": {
        "type": "validity-domain",
        "url": "https://github.com/open-science-pillars/marketplace/issues/27"},
    "dead-end-candidates": {
        "type": "dead-end",
        "url": "https://github.com/open-science-pillars/marketplace/issues/60"},
}


def route(topic: str) -> dict | None:
    """The register a bucket routes to, or None for the gotcha ladder."""
    return REGISTERS.get(topic)


def fetch_issues(repo: str, token: str | None, pages: int = 3) -> list:
    out = []
    for page in range(1, pages + 1):
        url = (f"https://api.github.com/repos/{repo}/issues"
               f"?state=all&per_page=100&page={page}")
        req = urllib.request.Request(url, headers={
            "User-Agent": "osp-nasa-daac-knowledge/1.0 (mine_sources)",
            **({"Authorization": f"Bearer {token}"} if token else {}),
        })
        with urllib.request.urlopen(req, timeout=30) as r:
            batch = json.loads(r.read().decode("utf-8"))
        if not isinstance(batch, list) or not batch:
            break
        out += [i for i in batch if "pull_request" not in i]
    return out


def cluster(issues: list) -> dict:
    hits = {k: [] for k in LEXICON}
    for i in issues:
        text = ((i.get("title") or "") + " " + (i.get("body") or "")).lower()
        for topic, needles in LEXICON.items():
            if any(n in text for n in needles):
                hits[topic].append({"title": i.get("title", ""),
                                    "url": i.get("html_url", "")})
    return hits


def draft(outdir: Path, topic: str, evidence: list) -> Path:
    outdir.mkdir(parents=True, exist_ok=True)
    today = datetime.date.today().isoformat()
    src = "\n".join(
        f"  - id: issue-{n}\n    resource: {e['url']}\n    title: \"{e['title'][:70]}\""
        for n, e in enumerate(evidence[:8], 1))
    reg = route(topic)
    if reg and reg["type"] == "dead-end":
        obs = "\n".join(
            f"  - {{ at: {today}, by: process:ingest-miner, source: issue-{n} }}"
            for n in range(1, min(len(evidence), 8) + 1))
        stub = f"""---
type: dead-end
title: "CANDIDATE ({topic}): {len(evidence)} community reports read like a dead end"
description: "Drafted from {len(evidence)} community reports; routed to the dead-end register, where a steward decides whether this is a dead-end, a gotcha, or noise."
tags: [ecco, candidate, dead-end]
status: draft
load_bearing: low
generated: {{ by: process:ingest-miner, at: {today}T00:00:00Z }}
subject: []
attempt: {{ goal: "STUB", method: "STUB" }}
failure: {{ symptom: "STUB", cause: unknown }}
observations:
{obs}
reopens_if: "STUB"
sources:
{src}
---

# Candidate: {topic}

Routed to the dead-end register: {reg["url"]}

# Attempted

STUB: the steward writes what was tried, citing the reports.

# Observed

STUB: the dated observations, one per report.

# Why it fails

STUB: the cause, or the word unknown.

# Reopens if

STUB: the change that would make the attempt worth retrying.
"""
        out = outdir / f"candidate-{topic}.md"
        out.write_text(stub, encoding="utf-8")
        return out
    routed = f"\nRouted to the {reg['type']} register: {reg['url']}\n" if reg else ""
    stub = f"""---
type: gotcha
title: CANDIDATE ({topic}): recurring community confusion
description: Drafted from {len(evidence)} community reports; steward decides if this is a trap, a docs gap, or noise.
tags: [ecco, candidate, {topic}]
status: draft
generated: {{ by: process:ingest-miner, at: {today}T00:00:00Z }}
sources:
{src}
---

# Candidate: {topic}
{routed}
STUB: {len(evidence)} community reports matched this topic. Steward
review decides the outcome: a new gotcha (write the fact and the
consequence), a link to an existing concept (deduplicate), or discard
(recorded in log.md either way, so recurrence keeps its history).
"""
    out = outdir / f"candidate-{topic}.md"
    out.write_text(stub, encoding="utf-8")
    return out


SELFTEST = [
    {"title": "Heat budget does not close on 0.5 deg interpolated fields",
     "body": "I regridded and the residual is huge", "html_url": "https://x/1"},
    {"title": "Budget residual large", "body": "am I missing geothermal flux?",
     "html_url": "https://x/2"},
    {"title": "401 from earthdata when downloading", "body": "netrc setup?",
     "html_url": "https://x/3"},
    {"title": "Interpolated budget question", "body": "latlon budget wrong",
     "html_url": "https://x/4"},
    # Three reports phrased as attempts that failed: the dead-end bucket,
    # routed to its register, clears the default --min-hits.
    {"title": "Tried closing the volume budget from monthly means, gave up",
     "body": "the residual never settles; dead end for this approach",
     "html_url": "https://x/5"},
    {"title": "Plotting tiles with pcolormesh does not work across the arctic",
     "body": "workaround was to plot tile by tile", "html_url": "https://x/6"},
    {"title": "Retracting my earlier fix for the proxy download",
     "body": "it failed because the mirror moved", "html_url": "https://x/7"},
]


def checker_lexicon() -> set | None:
    """The --candidates lexicon of check_negative.py beside this file, read
    from its source (the two scripts declare different dependencies, so
    neither imports the other); None when the checker is not beside us."""
    import ast
    src = Path(__file__).with_name("check_negative.py")
    if not src.exists():
        return None
    for node in ast.parse(src.read_text(encoding="utf-8")).body:
        if (isinstance(node, ast.Assign)
                and any(getattr(t, "id", None) == "LEXICON" for t in node.targets)):
            return set(ast.literal_eval(node.value))
    return None


def selftest() -> int:
    import tempfile
    hits = cluster(SELFTEST)
    ok = (len(hits["interpolated-budgets"]) == 2
          and len(hits["geothermal"]) == 1
          and len(hits["access-auth"]) == 1
          and len(hits["dead-end-candidates"]) == 3)
    print({k: len(v) for k, v in hits.items() if v})
    # Routing: the dead-end bucket names the dead-end register, the
    # validity-domain bucket names its own, a gotcha bucket names none,
    # and a drafted dead-end stub carries the register's type and URL.
    dead = route("dead-end-candidates")
    ok = ok and dead is not None and dead["type"] == "dead-end" \
        and dead["url"].endswith("/marketplace/issues/60")
    vd = route("validity-domain-candidates")
    ok = ok and vd is not None and vd["type"] == "validity-domain" \
        and vd["url"].endswith("/marketplace/issues/27")
    ok = ok and route("geothermal") is None
    with tempfile.TemporaryDirectory() as td:
        stub = draft(Path(td), "dead-end-candidates", hits["dead-end-candidates"]).read_text()
        ok = ok and stub.startswith("---\ntype: dead-end\n") and dead["url"] in stub \
            and stub.count("source: issue-") == 3
        gotcha = draft(Path(td), "geothermal", hits["geothermal"]).read_text()
        ok = ok and gotcha.startswith("---\ntype: gotcha\n") and "register" not in gotcha
    print("routing:", {k: v["type"] for k, v in REGISTERS.items()})
    # Lockstep with the checker's --candidates lexicon, when it is beside us.
    theirs = checker_lexicon()
    if theirs is not None:
        same = theirs == set(LEXICON["dead-end-candidates"])
        print("lexicon matches check_negative.py:", same)
        ok = ok and same
    print("selftest:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repos", nargs="+",
                    default=["ECCO-GROUP/ECCOv4-py",
                             "ECCO-GROUP/ECCO-v4-Python-Tutorial"])
    ap.add_argument("--min-hits", type=int, default=3)
    ap.add_argument("--draft-dir", type=Path)
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    token = os.environ.get("GITHUB_TOKEN")
    issues = []
    for repo in args.repos:
        batch = fetch_issues(repo, token)
        print(f"{repo}: {len(batch)} issues fetched")
        issues += batch

    hits = cluster(issues)
    for topic, ev in sorted(hits.items(), key=lambda kv: -len(kv[1])):
        if ev:
            reg = route(topic)
            tail = f"  -> {reg['type']} register {reg['url']}" if reg else ""
            print(f"{len(ev):>3}  {topic}{tail}")
    if args.draft_dir:
        drafted = 0
        for topic, ev in hits.items():
            if len(ev) >= args.min_hits:
                draft(args.draft_dir, topic, ev)
                drafted += 1
        print(f"drafted {drafted} candidate stub(s) -> {args.draft_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
