#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""mine_sources: harvest ECCO community issues, cluster recurring
confusions, and draft gotcha candidates for the promotion ladder.

Pulls issues (open and closed) from ECCO-GROUP repos via the GitHub API,
buckets them against a topic lexicon of known-confusable ECCO subjects,
and reports clusters by recurrence. With --draft-dir it writes one gotcha
candidate stub per cluster that clears --min-hits, each stub carrying its
evidence links (the issue URLs), generated by the miner's process actor,
status draft, unverified tier. Humans decide what is a real trap; the
miner only counts and cites.

Auth: set GITHUB_TOKEN (unauthenticated API rate limits are low). The
forum (ecco-group.org discussion board) has no API; it is read by hand
against the same lexicon.

Usage:
  mine_sources.py [--repos ECCO-GROUP/ECCOv4-py ECCO-GROUP/ECCO-v4-Python-Tutorial]
      [--min-hits 3] [--draft-dir out/] [--selftest]
"""

import argparse
import datetime
import json
import os
import re
import sys
import urllib.request
from pathlib import Path

LEXICON = {
    "interpolated-budgets": ["interpolat", "0.5 deg", "latlon budget", "regrid"],
    "snapshots-and-bookends": ["snapshot", "tendency", "bookend"],
    "geothermal": ["geothermal"],
    "hfac-partial-cells": ["hfac", "partial cell"],
    "release-mixing": ["v4r4b", "r4b", "release 4b", "mix release"],
    "llc-grid-orientation": ["llc", "tile", "face", "rotate", "orientation", "cs sn"],
    "access-auth": ["earthdata", "netrc", "401", "403", "credential", "authenticat"],
    "ecco-access-quirks": ["ecco_access", "ecco_podaac", "download fail", "filename"],
    "units-signs": ["sign convention", "units", "w/m2", "positive down", "positive up"],
    "bolus-transport": ["bolus", "gm ", "gent"],
    # Recurring can-I-use-X-for-Y questions are validity-domain
    # candidates; clusters here go to the validity-domain register
    # (open-science-pillars/marketplace#27), not the gotcha ladder.
    "validity-domain-candidates": ["can i use", "suitable for", "valid for",
                                   "appropriate for", "good enough for",
                                   "fit for", "reliable for", "trust the trend",
                                   "resolve eddies", "resolution enough"],
}


def fetch_issues(repo: str, token: str | None, pages: int = 3) -> list:
    out = []
    for page in range(1, pages + 1):
        url = (f"https://api.github.com/repos/{repo}/issues"
               f"?state=all&per_page=100&page={page}")
        req = urllib.request.Request(url, headers={
            "User-Agent": "osp-nasa-daac-knowledge/1.0 (mine_sources)",
            **({"Authorization": f"Bearer {token}"} if token else {}),
        })
        with urllib.request.urlopen(req, timeout=30) as r:
            batch = json.loads(r.read().decode("utf-8"))
        if not isinstance(batch, list) or not batch:
            break
        out += [i for i in batch if "pull_request" not in i]
    return out


def cluster(issues: list) -> dict:
    hits = {k: [] for k in LEXICON}
    for i in issues:
        text = ((i.get("title") or "") + " " + (i.get("body") or "")).lower()
        for topic, needles in LEXICON.items():
            if any(n in text for n in needles):
                hits[topic].append({"title": i.get("title", ""),
                                    "url": i.get("html_url", "")})
    return hits


def draft(outdir: Path, topic: str, evidence: list) -> None:
    outdir.mkdir(parents=True, exist_ok=True)
    today = datetime.date.today().isoformat()
    src = "\n".join(
        f"  - id: issue-{n}\n    resource: {e['url']}\n    title: \"{e['title'][:70]}\""
        for n, e in enumerate(evidence[:8], 1))
    stub = f"""---
type: gotcha
title: CANDIDATE ({topic}): recurring community confusion
description: Drafted from {len(evidence)} community reports; steward decides if this is a trap, a docs gap, or noise.
tags: [ecco, candidate, {topic}]
status: draft
generated: {{ by: process:ingest-miner, at: {today}T00:00:00Z }}
sources:
{src}
---

# Candidate: {topic}

STUB: {len(evidence)} community reports matched this topic. Steward
review decides the outcome: a new gotcha (write the fact and the
consequence), a link to an existing concept (deduplicate), or discard
(recorded in log.md either way, so recurrence keeps its history).
"""
    (outdir / f"candidate-{topic}.md").write_text(stub, encoding="utf-8")


SELFTEST = [
    {"title": "Heat budget does not close on 0.5 deg interpolated fields",
     "body": "I regridded and the residual is huge", "html_url": "https://x/1"},
    {"title": "Budget residual large", "body": "am I missing geothermal flux?",
     "html_url": "https://x/2"},
    {"title": "401 from earthdata when downloading", "body": "netrc setup?",
     "html_url": "https://x/3"},
    {"title": "Interpolated budget question", "body": "latlon budget wrong",
     "html_url": "https://x/4"},
]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repos", nargs="+",
                    default=["ECCO-GROUP/ECCOv4-py",
                             "ECCO-GROUP/ECCO-v4-Python-Tutorial"])
    ap.add_argument("--min-hits", type=int, default=3)
    ap.add_argument("--draft-dir", type=Path)
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        hits = cluster(SELFTEST)
        ok = (len(hits["interpolated-budgets"]) == 2
              and len(hits["geothermal"]) == 1
              and len(hits["access-auth"]) == 1)
        print({k: len(v) for k, v in hits.items() if v})
        print("selftest:", "PASS" if ok else "FAIL")
        return 0 if ok else 1

    token = os.environ.get("GITHUB_TOKEN")
    issues = []
    for repo in args.repos:
        batch = fetch_issues(repo, token)
        print(f"{repo}: {len(batch)} issues fetched")
        issues += batch

    hits = cluster(issues)
    for topic, ev in sorted(hits.items(), key=lambda kv: -len(kv[1])):
        if ev:
            print(f"{len(ev):>3}  {topic}")
    if args.draft_dir:
        drafted = 0
        for topic, ev in hits.items():
            if len(ev) >= args.min_hits:
                draft(args.draft_dir, topic, ev)
                drafted += 1
        print(f"drafted {drafted} candidate stub(s) -> {args.draft_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
